use std::collections::HashMap;
use std::fs;
use tempfile::TempDir;

#[test]
fn test_mise_config_to_toml_basic() {
    let mut tools = HashMap::new();
    tools.insert("node".to_string(), "25".to_string());
    tools.insert("go".to_string(), "latest".to_string());

    let config = mimic::mise::MiseConfig { tools };
    let toml = config.to_toml();

    assert!(toml.contains("# Generated by mimic"));
    assert!(toml.contains("[tools]"));
    assert!(toml.contains("node = \"25\""));
    assert!(toml.contains("go = \"latest\""));
}

#[test]
fn test_mise_config_sorted() {
    let mut tools = HashMap::new();
    tools.insert("z-tool".to_string(), "1.0".to_string());
    tools.insert("a-tool".to_string(), "2.0".to_string());
    tools.insert("m-tool".to_string(), "3.0".to_string());

    let config = mimic::mise::MiseConfig { tools };
    let toml = config.to_toml();

    let a_pos = toml.find("a-tool").unwrap();
    let m_pos = toml.find("m-tool").unwrap();
    let z_pos = toml.find("z-tool").unwrap();
    assert!(a_pos < m_pos, "a-tool should come before m-tool");
    assert!(m_pos < z_pos, "m-tool should come before z-tool");
}

#[test]
fn test_mise_config_write_creates_directories() {
    let temp = TempDir::new().unwrap();
    let nested_path = temp.path().join("deeply/nested/config.toml");

    let mut tools = HashMap::new();
    tools.insert("node".to_string(), "25".to_string());

    let config = mimic::mise::MiseConfig { tools };
    config.write_to_file(&nested_path).unwrap();

    assert!(nested_path.exists());
    let content = fs::read_to_string(&nested_path).unwrap();
    assert!(content.contains("node = \"25\""));
}

#[test]
fn test_mise_config_empty_tools() {
    let config = mimic::mise::MiseConfig {
        tools: HashMap::new(),
    };

    let toml = config.to_toml();
    assert!(toml.contains("[tools]"));

    let content_lines: Vec<_> = toml
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .collect();
    assert_eq!(content_lines.len(), 1);
    assert_eq!(content_lines[0], "[tools]");
}

#[test]
fn test_mise_special_tool_names() {
    let mut tools = HashMap::new();
    tools.insert("npm:@openai/codex".to_string(), "latest".to_string());
    tools.insert("asdf:neovim".to_string(), "nightly".to_string());
    tools.insert("bun".to_string(), "1.0.0".to_string());

    let config = mimic::mise::MiseConfig { tools };
    let toml = config.to_toml();

    assert!(
        toml.contains("\"npm:@openai/codex\" = \"latest\"")
            || toml.contains("'npm:@openai/codex' = \"latest\"")
    );
    assert!(
        toml.contains("\"asdf:neovim\" = \"nightly\"")
            || toml.contains("'asdf:neovim' = \"nightly\"")
    );
    assert!(toml.contains("bun = \"1.0.0\""));
}

#[test]
fn test_mise_config_write_and_read() {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join("config.toml");

    let mut tools = HashMap::new();
    tools.insert("node".to_string(), "25".to_string());
    tools.insert("go".to_string(), "latest".to_string());

    let config = mimic::mise::MiseConfig {
        tools: tools.clone(),
    };
    config.write_to_file(&path).unwrap();

    assert!(path.exists());
    let content = fs::read_to_string(&path).unwrap();

    assert!(content.contains("# Generated by mimic"));
    assert!(content.contains("[tools]"));
    assert!(content.contains("node = \"25\""));
    assert!(content.contains("go = \"latest\""));
}
