export ZDOTDIR="$HOME"

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

if [[ -f "$HOME/.cargo/env" ]]; then
    source "$HOME/.cargo/env"
fi

if command -v mise &> /dev/null; then
    eval "$(mise activate zsh)"
fi
