set nocompatible
syntax on
filetype plugin indent on

set number
set relativenumber
set ruler
set showcmd
set wildmenu

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set backspace=indent,eol,start

set background=dark
colorscheme desert

set laststatus=2

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

inoremap jk <ESC>
