export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

autoload -Uz compinit
compinit

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY

alias ls='exa --icons --group-directories-first'
alias ll='exa -lah --icons --group-directories-first'
alias tree='exa --tree --icons'
alias cat='bat'
alias grep='grep --color=auto'
alias vim='nvim'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph'

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
