use anyhow::{Context, Result};
use colored::Colorize;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone, Default)]
pub struct MiseConfig {
    pub tools: HashMap<String, String>,
}

impl MiseConfig {
    pub fn to_toml(&self) -> String {
        let mut lines = vec![
            "# Generated by mimic - do not edit manually".to_string(),
            "# Regenerate with: mimic apply".to_string(),
            "".to_string(),
            "[tools]".to_string(),
        ];

        let mut tools: Vec<_> = self.tools.iter().collect();
        tools.sort_by_key(|(k, _)| *k);

        for (tool, version) in tools {
            if needs_quoting(tool) {
                lines.push(format!("\"{}\" = \"{}\"", tool, version));
            } else {
                lines.push(format!("{} = \"{}\"", tool, version));
            }
        }

        let mut output = lines.join("\n");
        output.push('\n');
        output
    }

    pub fn write_to_file(&self, path: &PathBuf) -> Result<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
        }

        // Write via temp file + rename so an interrupted write can't leave a
        // truncated config for mise to choke on.
        let content = self.to_toml();
        let temp_path = path.with_extension("toml.tmp");
        fs::write(&temp_path, content)
            .with_context(|| format!("Failed to write mise config: {}", temp_path.display()))?;
        fs::rename(&temp_path, path)
            .with_context(|| format!("Failed to write mise config: {}", path.display()))?;

        Ok(())
    }

    pub fn default_path() -> Result<PathBuf> {
        let base_dirs = directories::BaseDirs::new()
            .ok_or_else(|| anyhow::anyhow!("Could not determine home directory"))?;
        let home = base_dirs.home_dir();
        Ok(home.join(".config/mise/config.toml"))
    }
}

/// Quote any key that is not a valid TOML bare key. Notably a `.` in an
/// unquoted key would create a nested table (`tools.foo.bar`) instead of a
/// tool literally named `foo.bar`.
fn needs_quoting(key: &str) -> bool {
    key.is_empty()
        || !key
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
}

pub fn generate_mise_config(config: &crate::config::Config) -> Result<()> {
    if config.mise.tools.is_empty() {
        return Ok(());
    }

    let mise_config = MiseConfig {
        tools: config.mise.tools.clone(),
    };

    let path = MiseConfig::default_path()?;
    mise_config.write_to_file(&path)?;

    println!(
        "  {} Generated mise config: {}",
        "→".bright_black(),
        path.display()
    );

    Ok(())
}
