set nocompatible
syntax on
filetype plugin indent on

set number
set relativenumber
set ruler
set showcmd
set wildmenu
set cursorline

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set backspace=indent,eol,start

set hidden
set splitbelow
set splitright

set mouse=a

set undofile
set undodir=~/.vim/undo
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/swap

if !isdirectory($HOME . "/.vim/undo")
    call mkdir($HOME . "/.vim/undo", "p")
endif
if !isdirectory($HOME . "/.vim/backup")
    call mkdir($HOME . "/.vim/backup", "p")
endif
if !isdirectory($HOME . "/.vim/swap")
    call mkdir($HOME . "/.vim/swap", "p")
endif

set background=dark
colorscheme desert

set laststatus=2
set statusline=%F\ %m%r%h%w\ [%{&ff}]\ [%Y]\ [%04l,%04v]\ [%p%%]\ [LEN=%L]

let mapleader = " "

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>h :noh<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

inoremap jk <ESC>

vnoremap < <gv
vnoremap > >gv
